### ISSUE TITLE
TargetException

### ISSUE THREAD

**Issue by pascallammers** [novitae/sterraxcyl#10]
Hey! 
When I scrape the followers of a specific account it starts but stops about 30-35% with that error message: 

`TargetException: Be sure that you are following the account you are aiming for if it is in private.`

Is there anything I can do about it? Didn't you had a delay function in your script?

**Comment by novitae** [comment]
Hi ! I am working on an update to add few functions as the delay. Sometimes it happens the program gets blocked by instagram around 300/400 followers, it happened to me too. For now try to change of account to do it, and if it gets blocked again, wait to the update ... im sorry i don't have any other solutions :(

I will also try to make a function that allows to export lists by parts, so when instagram blocks, it exports, you wait, and retry, and it gets the last part.
