### ISSUE TITLE
LoginError: Invalid sessid

### ISSUE THREAD

**Issue by thenib** [novitae/sterraxcyl#16]
As of today sterra began failing with LoginError: Invalid sessid, has instagram made changes?

**Comment by novitae** [comment]
yup, insta makes new sessions ids formats, so the regex check is failing. There's few other changes with rate limits, im gonna update that soon :)

**Comment by atz-spe** [comment]
@novitae, if you have any problem with new Instagram request parameters requirements, see => https://github.com/megadose/toutatis/pull/40
