### ISSUE TITLE
KeyError: 'The input list must contain (at least) the key "id"'

### ISSUE THREAD

**Issue by thenib** [novitae/sterraxcyl#19]
Following the example on on the wiki:  `sterra compare F_ID_1 F_ID_2 --common-usernames`

I have tried the full path to each of the files for comparison , also tried with the file ID's found listed in history for the files im trying to compare but both return `KeyError: 'The input list must contain (at least) the key "id"'`

Is this an issue or am I using it incorrectly?

**Comment by novitae** [comment]
This issue means that one of the lists doesn't contains the users, like each line contains "id", "username", "name" etc etc, that means userid is missing. If you are comparing lists of username, that's why.

**Comment by thenib** [comment]
Compare only works with lists which are exported containing "Default informations"?
In my case, my lists are exported with --only-usernames in csv format, will this result in the error I receive trying to compare with them?

**Comment by novitae** [comment]
yep it is from this, I can try to make an argument to compare anyway if you want to

**Comment by thenib** [comment]
If you could that would be appreciated
