### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ch4c4l** [novitae/sterraxcyl#2]
When performing a search as sterra -u xxxxx -t followers, (xxxxx I replace it with a user) I get the following error

Unknown error, here is the response:
{"message": "checkpoint_required", "checkpoint_url": "/ challenge / AXFDryCPIRfCXMzgUoVyguEOsXuhmBvRItoY27ajqfad1f7U-MaDLvlGFXsjnMnwgYVcr8A / OwJmxTBVrender:" flow "0", "lockty" status "flow" falsety} "lockty", falsety "lockty"} "flowtyVcr8A / OwJmxTBVrender:"

**Comment by novitae** [comment]
It seems instagram blocks you, or that your account has 2AF activated.
I had my first block yesterday, I just updated the repot add a function that print clearly if instagram detects you as spam
Update your version then tell me back what you get as error message :)
If you again do, try with another account that you never used for scraping

**Comment by ch4c4l** [comment]
I have changed my instagram account and it works. Surely the account that gave me an error would be because it had been blocked.

**Comment by novitae** [comment]
yeah, it is annoying but simply changing works, and if instagram blocks you from creating one, use a tor proxy configuration on your computer to access it without being blocked :)
