### ISSUE TITLE
Delay information 

### ISSUE THREAD

**Issue by thenib** [novitae/sterraxcyl#20]
What unit of time is delay in? 
What delay would be sufficient to collect "Default informations"?

**Comment by novitae** [comment]
> What unit of time is delay in?

Delay is in seconds, as integers arguments (`-d 1` -> `1 sec`).

> What delay would be sufficient to collect "Default informations"?

Delay is just there to put more time between requests to avoid getting ratelimited by Instagram. So, if by `Default informations` you mean all the follower/following, more delay you will have, less chances of getting blocked you will have, so more informations you will have.

**Comment by thenib** [comment]
So -d OR --delay can be used?

**Comment by novitae** [comment]
ye

**Comment by thenib** [comment]
Is there anther way to slow it down? Ive tired both but it still makes progress at the same rate as not specifying a delay

**Comment by novitae** [comment]
no
