### ISSUE TITLE
Call Sterra commands directly from python

### ISSUE THREAD

**Issue by MiniMinnoww** [novitae/sterraxcyl#23]
I'm trying to call sterra command directly from python, however subprocess cannot find the command? Is there a better way I should be doing this?

**Comment by novitae** [comment]
Well, what you can do is
```py
from sterra.core import main, _parser
```
Follow the next step precisely !
- In sterra.core, copy from `line 187` to `line 419` (so the whole `_parser` function)
- Paste it in your file
- Make the necessary imports so this paster `_parser` function can run
- Modify its name to whatever you want (in my example `my_pasted_parser_name`)
- Add an argument which will be your command under list of string format:
```py
def _parser() -> tuple:
# Becomes:
def my_pasted_parser_name(my_command: list[str] = ["MY", "REAL", "COMMAND"]) -> tuple:
# By making `my_command` being equal by default to your wanted command,
# it will automatically place it since sterra's `main` function won't put args in it
```
- At line `args = parser.parse_args()`, replace by `args = parser.parse_args(my_command)` (`line 414`)
- Then, and do:
```py
_parser = my_pasted_parser_name

if __name__ == "__main__":
    main() # Here you run sterra's `main`
```
A bit complicated but it should work

**Comment by MiniMinnoww** [comment]
> 

Thanks. Also another thing, when using 'sterra history -i FILE_ID' it says it found the file path, but doesn't actually say the file path

**Comment by MiniMinnoww** [comment]
Sorry I'm back. There are a couple things happening here. Mainly, I am finding that when using `sterra export` the file isn't actually being created (the function is just returning the arguments). Here is my code:

https://pastebin.com/G7Pu8SVs

**Comment by novitae** [comment]
It is because you are just running the parser of sterra, nothing else. If you don't run sterra's `main` function, it won't generate or scrape anything. As I said in the first and last line of my last answer:
```python
from sterra.core import main, _parser
```
```python
if __name__ == "__main__":
    main() # Here you run sterra's `main`
```

**Comment by MiniMinnoww** [comment]
> It is because you are just running the parser of sterra, nothing else. If you don't run sterra's `main` function, it won't generate or scrape anything. As I said in the first and last line of my last answer:
> 
> ```python
> from sterra.core import main, _parser
> ```
> 
> ```python
> if __name__ == "__main__":
>     main() # Here you run sterra's `main`
> ```

I have added the running of main here: https://pastebin.com/T3xdg2GG
However, it just prints out the default print (not the export not with arguments).
Might be worth noting PyCharm thinks the _parser import is unessecarry?
