### ISSUE TITLE
RateLimitError & Part not being created

### ISSUE THREAD

**Issue by yada-yoda** [novitae/sterraxcyl#30]
`-d ` switch for delay does not work when using export command:
`sterra export -ssid redactedssid -u usernameredacted -t followers -f csv -d 900`

Assuming this delay also changes the fixed "sleeping 10 sec" attempt delay when exporting followers, it does not change this either.

When exporting, the "part" is never created in %appdata% module folder, even with admin permissions. A `RateLimitError` occurs, but a `PART_ID` is never assigned, if started again it doesn't continue where it left off on exporting followers, therefore starting the process over again.

```
|x| Target > userredacted (39240 followers, 802 following)
|§| Followers extraction:  24%|██▍       | 9465/39240 [01:00<03:54, 126.90it/s]1/3 attempts, sleeping 10 sec
2/3 attempts, sleeping 10 sec
|§| Followers extraction:  24%|██▍       | 9510/39240 [01:20<03:54, 126.90it/s]3/3 attempts, sleeping 10 sec
|§| Followers extraction:  24%|██▍       | 9510/39240 [01:31<04:44, 104.49it/s]
|!| RateLimitError: Rate limit at Rate limit happenning during list of follows scraping. Wait a bit, or change of login account. blocks the program. Wait a bit, or change of login account.
```

Also small spelling error, happenning should be happening.

**Comment by novitae** [comment]
The `PART_ID` is only made when scraping informations about all the accounts. The rate limit you are experiencing is during the username scraping, not the informations.
