### ISSUE TITLE
Add the possibility to use a list of credentials and a list of target profiles

### ISSUE THREAD

**Issue by hpiedcoq** [novitae/sterraxcyl#6]
Very nice tool!

It could be interesting to have an option to import a csv file of accounts credentials, and use this list to avoid blocking by the plateform. (rotate users).

You could then also add an option to add a list of targets, to scrape several profiles.

**Comment by novitae** [comment]
rotating accounts idea not needed anymore, replaced soon with an export by part (if the export gets blocked)
