### ISSUE TITLE
Problem from the instalation part

### ISSUE THREAD

**Issue by Saturnot** [novitae/sterraxcyl#9]
I've got to many error while I'm trying to install the git:
![Screenshot 2021-11-16 22:18:06](https://user-images.githubusercontent.com/64526188/142067341-1b3a90bc-17e5-41f7-8c62-1c3c1c49eb82.png)

**Comment by novitae** [comment]
try `sudo python setup.py install`
if it don't works, try `pip install sterrarxcyl`

**Comment by Saturnot** [comment]
It work better with pip thanks !
